logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    io.github.wizwix: DEBUG
  pattern.console: "%clr(%d{yy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
spring:
  application:
    name: campus-facility-management-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/campus?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul'
    username: root
    password: mysql
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 3000
  devtools:
    livereload:
      enabled: true
      port: 35729 # Default value. Leave this for later reference.
    restart:
      enabled: true
  jackson:
    parser:
      allow-comments: true
      allow-trailing-comma: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  #  main:
  #    allow-bean-definition-overriding: true
  mvc:
    format:
      date: 'yyyy-MM-dd'
      date-time: "yyyy-MM-dd'T'HH:mm:ss"
  sql:
    init:
      encoding: utf-8
jwt:
  secret: "${JWT_SECRET:XnU6QEqivzFIBkPC70xQr5KI3y5HBbsUXnU6QEqivzFIBkPC70xQr5KI3y5HBbsU}"
  expiration: 3600000 # 1 hour
